---
# tasks file for roles/global_posix_capabilities_check
#------------------------------------------- 
- debug: msg="++++++++++++++++++++++++ TASK - CALL posix_capabilities.yml ++++++++++++++++++++++++"
- name: posix capabilities | CHECK File Permissions and Masks
  import_tasks: posix_capabilities.yml
  tags:
    - posix_capabilities
    - global_posix_capabilities_check
  ignore_errors: yes
#-------------------------------------------
...